### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by johnfelipe** [SanjayMarreddi/ML_Internship_Technocolabs#63] opened 2021-06-12 22:20 UTC
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
    Traceback:
    File "/usr/local/lib/python3.8/dist-packages/streamlit/script_runner.py", line 338, in _run_script
        exec(code, module.__dict__)
    File "/root/Emotion-Investigator/main.py", line 3, in <module>
        import cv2
    File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 5, in <module>
        from .cv2 import *

how solved?

**Comment by SanjayMarreddi** [comment] 2021-06-13 04:10
@johnfelipe Hi,
Looks like the dependencies are not perfectly installed.

Also, after browsing the web, I came to know that the problem is with the Installation of **OpenCV** in your system, Nothing to do specifically with our Project. 

Kindly refer to [this](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo) to resolve your OpenCV issue.

Thanks!

**Comment by johnfelipe** [comment] 2021-06-13 04:20
git clone https://github.com/SanjayMarreddi/Emotion-Investigator.git
    cd Emotion-Investigator
    pip install -r requirements.txt
    apt-get install ffmpeg libsm6 libxext6  -y
    python3 main.py

and show me this:

    2021-06-13 04:18:11.922688: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
    2021-06-13 04:18:11.922729: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
    /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
      warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
    2021-06-13 04:18:13.259252: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
    2021-06-13 04:18:13.259300: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
    2021-06-13 04:18:13.259331: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (uno-ubuntu-s-8vcpu-16gb-nyc1-01): /proc/driver/nvidia/version does not exist
    2021-06-13 04:18:13.259677: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
    To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
     * Serving Flask app "main" (lazy loading)
     * Environment: production
       WARNING: This is a development server. Do not use it in a production deployment.
       Use a production WSGI server instead.
     * Debug mode: on
     * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
     * Restarting with inotify reloader
    2021-06-13 04:18:14.956370: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
    2021-06-13 04:18:14.956415: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
    /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
      warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
    2021-06-13 04:18:16.191303: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
    2021-06-13 04:18:16.191344: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
    2021-06-13 04:18:16.191367: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (uno-ubuntu-s-8vcpu-16gb-nyc1-01): /proc/driver/nvidia/version does not exist
    2021-06-13 04:18:16.191610: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
    To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
     * Debugger is active!
     * Debugger PIN: 312-763-093

but how can deploy in my public ip?

**Comment by SanjayMarreddi** [comment] 2021-06-13 04:52
Currently, our project is being developed on the Local System only. We haven't deployed it yet. Although I tried deploying it on HEROKU, due to free tier limits ( Slug Size ), I stopped in the middle.

Anyways, If you want to deploy it, you can try using other cloud services.

**Comment by johnfelipe** [comment] 2021-06-13 05:28
but i need only change

    Running on http://127.0.0.1:5000/

for 0.0.0.0

pls help me for test and review and collaborate
Tnks

**Comment by SanjayMarreddi** [comment] 2021-06-13 05:39
I don't think there is a way to change `Running on http://127.0.0.1:5000/` to `0.0.0.0` directly.  At least I don't know how to do it. Actually, Flask by default has mode: `Running on http://127.0.0.1:5000/` Ig. **As per my knowledge, Deployment on Cloud Services can be done or some tweaking of the Flask settings.**

Anyways, Ig this is not the right place to ask for `pls help me for test and review and collaborate` Ig. 

Please ask your tech stack-related questions on **forums** since they are not specific to the project.

Also, the Issue you opened is resolved. So I am closing it.

Thanks & Good Luck!

**Closed as completed by SanjayMarreddi** 2021-06-13 05:39 UTC
Labels: bug
